# Generated by Django 4.1.7 on 2023-03-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('context', models.TextField(max_length=255)),
                ('author', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
