# Generated by Django 4.1.7 on 2023-03-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
